-- Hideout Pickleball Club schema
-- Run this in Supabase SQL editor. Safe to re-run.

create extension if not exists pgcrypto;

create table if not exists public.courts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  status text not null default 'available',
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  court_id bigint not null references public.courts(id) on delete restrict,
  player_name text not null,
  player_email text not null,
  player_phone text,
  start_at timestamptz not null,
  end_at timestamptz not null,
  total_price numeric(10,2) not null,
  status text not null default 'pending',
  notes text,
  created_at timestamptz not null default now(),
  constraint bookings_valid_time check (start_at < end_at)
);

create table if not exists public.blocked_schedules (
  id uuid primary key default gen_random_uuid(),
  court_id bigint not null references public.courts(id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz not null,
  reason text,
  created_at timestamptz not null default now(),
  constraint blocked_valid_time check (start_at < end_at)
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete cascade,
  amount numeric(10,2) not null,
  method text,
  status text not null default 'pending',
  reference_no text,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'bookings'
      and column_name = 'payment_receipt_url'
  ) then
    alter table public.bookings add column payment_receipt_url text;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'courts'
      and column_name = 'status'
  ) then
    alter table public.courts add column status text not null default 'available';
  end if;
end
$$;

create index if not exists idx_bookings_court_time on public.bookings(court_id, start_at, end_at);
create index if not exists idx_blocked_court_time on public.blocked_schedules(court_id, start_at, end_at);

insert into public.courts (name)
values ('Court 1'), ('Court 2')
on conflict (name) do nothing;

alter table public.courts enable row level security;
alter table public.bookings enable row level security;
alter table public.blocked_schedules enable row level security;
alter table public.payments enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.courts to anon, authenticated;
grant select, insert on public.bookings to anon, authenticated;
grant update on public.bookings to anon, authenticated;
grant select on public.blocked_schedules to anon, authenticated;
grant select, insert on public.blocked_schedules to anon, authenticated;
grant select, insert on public.payments to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'courts' and policyname = 'public read courts'
  ) then
    create policy "public read courts" on public.courts for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'bookings' and policyname = 'public read bookings'
  ) then
    create policy "public read bookings" on public.bookings for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'bookings' and policyname = 'public insert bookings'
  ) then
    create policy "public insert bookings" on public.bookings for insert with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'bookings' and policyname = 'public update bookings'
  ) then
    create policy "public update bookings" on public.bookings for update using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'blocked_schedules' and policyname = 'public read blocked'
  ) then
    create policy "public read blocked" on public.blocked_schedules for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'blocked_schedules' and policyname = 'public insert blocked'
  ) then
    create policy "public insert blocked" on public.blocked_schedules for insert with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'blocked_schedules' and policyname = 'public delete blocked'
  ) then
    create policy "public delete blocked" on public.blocked_schedules for delete using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'payments' and policyname = 'public read payments'
  ) then
    create policy "public read payments" on public.payments for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'payments' and policyname = 'public insert payments'
  ) then
    create policy "public insert payments" on public.payments for insert with check (true);
  end if;
end
$$;

-- Storage bucket for payment receipts
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('receipts', 'receipts', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public uploads allowed'
  ) then
    create policy "Public uploads allowed" on storage.objects for insert to public with check (bucket_id = 'receipts');
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public read allowed'
  ) then
    create policy "Public read allowed" on storage.objects for select to public using (bucket_id = 'receipts');
  end if;
end
$$;
