-- Hideout Pickleball Club schema
-- Run this in Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.courts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'booking_status'
      and n.nspname = 'public'
  ) then
    create type public.booking_status as enum ('pending', 'confirmed', 'cancelled');
  end if;
end
$$;

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  court_id bigint not null references public.courts(id) on delete restrict,
  player_name text not null,
  player_email text not null,
  player_phone text,
  start_at timestamptz not null,
  end_at timestamptz not null,
  total_price numeric(10,2) not null,
  status public.booking_status not null default 'pending',
  notes text,
  created_at timestamptz not null default now(),
  constraint bookings_valid_time check (start_at < end_at)
);

create table if not exists public.blocked_schedules (
  id uuid primary key default gen_random_uuid(),
  court_id bigint not null references public.courts(id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz not null,
  reason text,
  created_at timestamptz not null default now(),
  constraint blocked_valid_time check (start_at < end_at)
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete cascade,
  amount numeric(10,2) not null,
  method text,
  status text not null default 'pending',
  reference_no text,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_bookings_court_time on public.bookings(court_id, start_at, end_at);
create index if not exists idx_blocked_court_time on public.blocked_schedules(court_id, start_at, end_at);

insert into public.courts (name)
values ('Court 1'), ('Court 2')
on conflict (name) do nothing;

-- Minimal RLS baseline (adjust to your auth model)
alter table public.courts enable row level security;
alter table public.bookings enable row level security;
alter table public.blocked_schedules enable row level security;
alter table public.payments enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.courts to anon, authenticated;
grant select, insert on public.bookings to anon, authenticated;
grant select on public.blocked_schedules to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'courts' and policyname = 'public read courts'
  ) then
    create policy "public read courts" on public.courts for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'bookings' and policyname = 'public read bookings'
  ) then
    create policy "public read bookings" on public.bookings for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'bookings' and policyname = 'public insert bookings'
  ) then
    create policy "public insert bookings" on public.bookings for insert with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'blocked_schedules' and policyname = 'public read blocked'
  ) then
    create policy "public read blocked" on public.blocked_schedules for select using (true);
  end if;
end
$$;
